### ISSUE TITLE
Missing source ftools_utils.py

### ISSUE THREAD

**Issue by magerlin** [LCacheux68224/Oursins#5]
In Qgis 2.16.1 ftools is no longer a plugin. Oursins seems to refer to file "ftools_utils.py" which is no longer existing.

2016-08-15T12:37:01	1	Traceback (most recent call last):
			  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 333, in startPlugin
			    plugins[packageName] = package.classFactory(iface)
			  File "C:/Users/MAP/.qgis2/python/plugins\Oursins\__init__.py", line 26, in classFactory
			    from oursins import Oursins
			  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/Users/MAP/.qgis2/python/plugins\Oursins\oursins.py", line 29, in <module>
			    from oursinsdialog import OursinsDialog
			  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/Users/MAP/.qgis2/python/plugins\Oursins\oursinsdialog.py", line 32, in <module>
			    ftu = imp.load_source('ftools_utils', os.path.join(path,'tools','ftools_utils.py'))
			IOError: [Errno 2] No such file or directory

**Comment by LCacheux68224** [comment]
Thank you.
I removed the dependency to ftools. The correction just uploaded should be available shortly.
